### ISSUE TITLE
Certbot should auto-update https certificate used in nginx (inside frontend)

### ISSUE THREAD

**Issue by sealexan** [mp-access/Infrastructure-Re#4]
The cert expires without notice after 3 months.

**Comment by ofvalentine** [comment]
Semi-automated - need to execute the following every 2-3 months:
* Run `docker compose up certbot` 
* Wait for the execution to finish
* Run `docker compose up frontend` 

Note that while running the last command, the frontend will be down (expects to take ~30s).
